# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d611fbe08cf0a5671b228a9ed887de20d5b7cbae49c1dd33ac47dc90aedafc91601440e59e7e879b63b990c4e57b6446bc530b2207749b98f51d4c0717c147

test:
  secret_key_base: c16033f589be193c0f2960081dddc35a45c912ae8dfbb39ec2f7ba39e90e4ed58c400bef6cc080448e356b2d60994d0eacd59ea173512f28791ea55a6e7efe4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
